# Generated by Django 5.1.2 on 2025-02-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("integration", models.CharField(max_length=50)),
                (
                    "assistant_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("chat_id", models.CharField(max_length=100)),
                ("thread_id", models.CharField(blank=True, max_length=100, null=True)),
                ("date_of_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("integration", "chat_id")},
            },
        ),
    ]
